apiVersion: v1
kind: ConfigMap
metadata:
  name: api-cm-config
data:
  # property-like keys; each key maps to a simple value
  default.toml: |
    {{ range .Values.api.additionalConfig }}
    {{ . }}
    {{ end }}

    blockList = "blocklist"

    [isolates]
      endpoint = "dns2:///{{ include "direktiv.fullname" . }}-isolates-hl.{{ .Release.Namespace }}:5555"

    [ingress]
      endpoint = "dns2:///{{ include "direktiv.fullname" . }}-ingress-hl.{{ .Release.Namespace }}:6666"
      
    [server]
      bind = ":8080"

    [templates]
      [[workflowTemplateDirectories]]
        name = "default"
        directory = "/tmp/workflow-templates"

      [[actionTemplateDirectories]]
        name = "default"
        directory = "/tmp/action-templates"
