apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "direktiv.fullname" . }}-ingress
  labels:
    {{- include "direktiv.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingressClass }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: 
    http:
      paths:
        - path: /api/*
          backend:
            serviceName: {{ include "direktiv.fullname" . }}-api-service
            servicePort: 8080
        - path: /*
          backend:
            serviceName: {{ include "direktiv.fullname" . }}-ui
            servicePort: 80