apiVersion: v1
kind: Service
metadata:
  name: {{ include "direktiv.fullname" . }}-isolates
  labels:
    {{- include "direktiv.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 5555
      name: grpc
      protocol: TCP
      nodePort: 30234
  selector:
    {{- include "direktiv.selectorLabels" . | nindent 4 }}-isolates
