apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "direktiv.fullname" . }}-isolates
  labels:
    {{- include "direktiv.labels" . | nindent 4 }}-isolates
spec:
  replicas: {{ .Values.isolates.replicaCount }}
  selector:
    matchLabels:
      {{- include "direktiv.selectorLabels" . | nindent 6 }}-isolates
  template:
    metadata:
      labels:
        {{- include "direktiv.selectorLabels" . | nindent 8 }}-isolates
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 33333
        runAsGroup: 22222
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "direktiv.serviceAccountName" . }}-isolate
      volumes:
        - name: config-file
          configMap:
            name: {{ include "direktiv.fullname" . }}-config-isolate
        {{- if ne  .Values.flow.certificate "none" }}
        - name: certs
          secret:
            secretName: {{ .Values.flow.certificate }}
        {{- end }}
      containers:
{{- if .Values.isolates.extraContainers }}
{{ toYaml .Values.isolates.extraContainers | indent 8}}
{{- end }}
        - name: isolate-controller
          volumeMounts:
          {{- if ne .Values.flow.certificate "none" }}
          - name: certs
            mountPath: "/etc/certs/direktiv"
            readOnly: true
          {{- end }}
          - name: config-file
            mountPath: /etc/direktiv
          env:
            {{- if .Values.isolates.debug }}
            - name: DIREKTIV_DEBUG
              value: "true"
            {{- end }}
            - name: DIREKTIV_LOCK_CM
              value: {{ include "direktiv.fullname" . }}-lock-cm
            - name: DIREKTIV_KUBERNETES_NAMESPACE
              value: {{ .Release.Namespace }}
            - name: "DIREKTIV_FLOW_ENDPOINT"
              value: "dns2:///{{ include "direktiv.fullname" . }}-flow-hl.{{ .Release.Namespace }}:7777"
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "1"
          image: "{{ .Values.registry }}/{{ .Values.isolates.image }}:{{ .Values.flow.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.pullPolicy }}
          ports:
            - name: grpc
              containerPort: 5555
              protocol: TCP
