{{- if (eq .Values.withIsolate true) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "direktiv.fullname" . }}-isolate
  labels:
    {{- include "direktiv.labels" . | nindent 4 }}-isolate
type: Opaque
data:
  exchangeKey: {{ .Values.isolate.exchange | b64enc | quote }}
{{- end}}
