apiVersion: v1
kind: ConfigMap
metadata:
  name: service-template
data:
  template: |
    {
      "apiVersion": "serving.knative.dev/v1",
      "kind": "Service",
      "metadata": {
        "name": "%s",
        "namespace": "{{ .Release.Namespace }}",
        "labels": {
          "networking.knative.dev/visibility": "cluster-local"
        }
      },
      "spec": {
        "template": {
          "metadata": {
            "annotations": {
              "autoscaling.knative.dev/minScale": "%d"
            }
          },
          "spec": {
            "serviceAccountName": "%s",
            "containers": [
              {
                "image": "%s",
    						"resources": {
                  "requests": {
                    "cpu": %f,
                    "memory": "%s"
                  },
                  "limits": {
                    "cpu": %f,
                    "memory": "%s"
                  }
                }
              },
              {
                "image": "%s",
                "env": [
                  {
                    "name": "DIREKTIV_DB",
                    "valueFrom": {
                      "secretKeyRef": {
                        "name": "{{ include "direktiv.fullname" . }}",
                        "key": "db"
                      }
                    }
                  }
                ],
                "ports": [
                  {
                    "containerPort": 8889
                  }
                ],
                "volumeMounts": [
                  {{- if ne (default .Values.certificate "none") "none" }}
                  {
                    "name": "certs",
                    "mountPath": "/etc/certs/direktiv",
                    "readOnly": true
                  },
                  {{- end }}
                  {
                    "name": "exchange",
                    "mountPath": "/var/secret"
                  }
                ]
              }
            ],
            "volumes": [
              {{- if ne (default .Values.certificate "none") "none" }}
              {
                "name": "certs",
                "secret": {
                  "secretName": "{{ include "direktiv.fullname" . }}-tls-secret"
                }
                },
              {{- end }}
              {
                "name": "exchange",
                "secret": {
                  "secretName": "{{- .Release.Name }}-isolate"
                }
              }
            ]
          }
        }
      }
    }
