kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: sidecar-role
 labels:
   {{- include "direktiv.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["services", "endpoints"]
  verbs: ["get", "list", "watch"]
