{{- if .Values.withUI -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "direktiv.fullname" . }}-ui
  labels:
    {{- include "direktiv.labelsUI" . | nindent 4 }}
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: ui
  selector:
    {{- include "direktiv.selectorLabelsUI" . | nindent 4 }}
{{- end }}
