name: Example Workflow Using SecureStack Secrets Scan Action
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo for running secrets analysis within workflow
        id: checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - name: Secrets Analysis Step
        id: secrets
        uses: SecureStackCo/actions-secrets@v0.1.0
        with:
          securestack_api_key: ${{ secrets.BH_API_KEY }}
          securestack_app_id: '0bdba4f4-33fa-4919-afa3-c742f26c7838'
          severity: critical
          flags: '-d 50'
